### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'createContext')

### ISSUE THREAD

**Issue by BillionShields** [sushanthr/RapidEsrGan#1]
I enabled WebNN in chrome still getting TypeError: Cannot read properties of undefined (reading 'createContext')
![Clipboard07](https://github.com/sushanthr/RapidEsrGan/assets/4848738/4a88ee5f-b9f8-457a-9333-cc3c21e36bfb)

**Comment by sushanthr** [comment]
Hello, 

WebNN is a nascent standard, eventually there should be broader adoption. For now, a windows machine with the latest Chrome/Edge Canary build should have all the Operators necessary for this to work.
